version: "3.7"

services:
  app:
    image: qrichert/goji
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./var/log/apache:/var/log/apache2"  # Apache log files
      - "./var/log/php:/var/log/php"  # PHP log files
      - ".:/var/www/html"  # App source code
