version: "3.7"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
#      - ./var:/var/www/html/var
      - ./var/log/apache2:/var/log/apache2
      - ./var/log/php:/var/log/php
