version: "3.7"

services:
  app:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./var:/var/www/html/var"
      - "./var/log/apache2:/var/log/apache2"
      - "./var/log/php:/var/log/php"
