version: "3.7"

services:
  app:
    #image: qrichert/goji
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./var/log/apache2:/var/log/apache2"
      - "./var/log/php:/var/log/php"
      - ".:/var/www/html"
