<?php

	namespace Goji\Blueprints;


	/**
	 * Interface HttpStatusInterface
	 *
	 * @package Goji\Blueprints
	 */
	interface HttpStatusInterface {

		const HTTP_INFORMATION_CONTINUE = 100;
		const HTTP_INFORMATION_SWITCHING_PROTOCOLS = 101;
		const HTTP_INFORMATION_PROCESSING = 102;
		const HTTP_INFORMATION_EARLY_HINTS = 103;

		const HTTP_SUCCESS_OK = 200;
		const HTTP_SUCCESS_ACCEPTED = 202;
		const HTTP_SUCCESS_NON_AUTHORITATIVE_INFORMATION = 203;
		const HTTP_SUCCESS_NO_CONTENT = 204;
		const HTTP_SUCCESS_RESET_CONTENT = 205;
		const HTTP_SUCCESS_PARTIAL_CONTENT = 206;
		const HTTP_SUCCESS_MULTI_STATUS = 207;
		const HTTP_SUCCESS_ALREADY_REPORTED = 208;
		const HTTP_SUCCESS_CONTENT_DIFFERENT = 210;
		const HTTP_SUCCESS_IM_USED = 226;

		const HTTP_REDIRECT_MULTIPLE_CHOICES = 300;
		const HTTP_REDIRECT_MOVED_PERMANENTLY = 301;
		const HTTP_REDIRECT_FOUND = 302;
		const HTTP_REDIRECT_SEE_OTHER = 303;
		const HTTP_REDIRECT_NOT_MODIFIED = 304;
		const HTTP_REDIRECT_USE_PROXY = 305;
		const HTTP_REDIRECT_SWITCH_PROXY = 306;
		const HTTP_REDIRECT_TEMPORARY_REDIRECT = 307;
		const HTTP_REDIRECT_PERMANENT_REDIRECT = 308;
		const HTTP_REDIRECT_TOO_MANY_REDIRECTS = 310;

		const HTTP_ERROR_BAD_REQUEST = 400;
		const HTTP_ERROR_UNAUTHORIZED = 401;
		const HTTP_ERROR_PAYMENT_REQUIRED = 402;
		const HTTP_ERROR_FORBIDDEN = 403;
		const HTTP_ERROR_NOT_FOUND = 404;
		const HTTP_ERROR_METHOD_NOT_ALLOWED = 405;
		const HTTP_ERROR_NOT_ACCEPTABLE = 406;
		const HTTP_ERROR_PROXY_AUTHENTICATION_REQUIRED = 407;
		const HTTP_ERROR_REQUEST_TIME_OUT = 408;
		const HTTP_ERROR_CONFLICT = 409;
		const HTTP_ERROR_GONE = 410;
		const HTTP_ERROR_LENGTH_REQUIRED = 411;
		const HTTP_ERROR_PRECONDITION_FAILED = 412;
		const HTTP_ERROR_REQUEST_ENTITY_TOO_LARGE = 413;
		const HTTP_ERROR_REQUEST_URI_TOO_LONG = 414;
		const HTTP_ERROR_UNSUPPORTED_MEDIA_TYPE = 415;
		const HTTP_ERROR_REQUESTED_RANGE_UNSATISFIABLE = 416;
		const HTTP_ERROR_EXPECTATION_FAILED = 417;
		const HTTP_ERROR_I_M_A_TEAPOT = 418;
		const HTTP_ERROR_BAD_MAPPING = 421;
		const HTTP_ERROR_UNPROCESSABLE_ENTITY = 422;
		const HTTP_ERROR_LOCKED = 423;
		const HTTP_ERROR_METHOD_FAILURE = 424;
		const HTTP_ERROR_UNORDERED_COLLECTION = 425;
		const HTTP_ERROR_UPGRADE_REQUIRED = 426;
		const HTTP_ERROR_PRECONDITION_REQUIRED = 428;
		const HTTP_ERROR_TOO_MANY_REQUESTS = 429;
		const HTTP_ERROR_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
		const HTTP_ERROR_RETRY_WITH = 449;
		const HTTP_ERROR_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450;
		const HTTP_ERROR_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
		const HTTP_ERROR_UNRECOVERABLE_ERROR = 456;

		const HTTP_ERROR_NO_RESPONSE = 444;
		const HTTP_ERROR_SSL_CERTIFICATE_ERROR = 495;
		const HTTP_ERROR_SSL_CERTIFICATE_REQUIRED = 496;
		const HTTP_ERROR_HTTP_REQUEST_SENT_TO_HTTPS_PORT = 497;
		const HTTP_ERROR_TOKEN_INVALID = 498;
		const HTTP_ERROR_CLIENT_CLOSED_REQUEST = 499;

		const HTTP_SERVER_INTERNAL_SERVER_ERROR = 500;
		const HTTP_SERVER_NOT_IMPLEMENTED = 501;
		const HTTP_SERVER_BAD_GATEWAY_OU_PROXY_ERROR = 502;
		const HTTP_SERVER_SERVICE_UNAVAILABLE = 503;
		const HTTP_SERVER_GATEWAY_TIME_OUT = 504;
		const HTTP_SERVER_HTTP_VERSION_NOT_SUPPORTED = 505;
		const HTTP_SERVER_VARIANT_ALSO_NEGOTIATES = 506;
		const HTTP_SERVER_INSUFFICIENT_STORAGE = 507;
		const HTTP_SERVER_LOOP_DETECTED = 508;
		const HTTP_SERVER_BANDWIDTH_LIMIT_EXCEEDED = 509;
		const HTTP_SERVER_NOT_EXTENDED = 510;
		const HTTP_SERVER_NETWORK_AUTHENTICATION_REQUIRED = 511;

		const HTTP_SERVER_UNKNOWN_ERROR = 520;
		const HTTP_SERVER_WEB_SERVER_IS_DOWN = 521;
		const HTTP_SERVER_CONNECTION_TIMED_OUT = 522;
		const HTTP_SERVER_ORIGIN_IS_UNREACHABLE = 523;
		const HTTP_SERVER_A_TIMEOUT_OCCURRED = 524;
		const HTTP_SERVER_SSL_HANDSHAKE_FAILED = 525;
		const HTTP_SERVER_INVALID_SSL_CERTIFICATE = 526;
		const HTTP_SERVER_RAILGUN_ERROR = 527;
	}
